config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "boards#index"

  resources :boards do
    resources :songs
  end

  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :artist, presence: true, uniqueness: true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :board, optional: true

  validates :song, :song_rank, uniqueness: true, presence: true
  validates :song_rank, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boards
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :_last_name])
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  def index
    @artists = Artist.all.sort_by { |a| a.artist}
  end
  
  def show
  end 
  
  def new
    @artist = Artist.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to artists_path
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:artist, :genre)
  end



end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = current_user.boards
  end

  def show
    @board_songs = Song.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.new(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private
    def board_params
      params.require(:board).permit(:name, :description)
    end

    def set_board
      @board = current_user.boards.find(params[:id])
    end
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @song = @artist.songs.new
  end

  def edit
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to [@artist, @song]
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to [@artist, @song]
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path
  end

  private
    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:song,:board_id)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_with(model: @artist, local: true, class: "ui form") do |f| %>
  <div class= "field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>
  <br />
  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>
  <hr />
  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", artist: @artist %>

<%= link_to "Show", artist_path(@artist) %> |
<%= link_to "Back", artists_path %>

app/views/artists/index.html.erb
<h1 class="ui header"><strong>All Artists</strong></h1>
<hr />
<%= link_to "New Artist", new_artist_path %>
<hr />
<% @artists.each do |artist| %>
  <h1><%= artist.artist %></h1>
  <%= link_to "See Artist's Songs", artist_songs_path(artist) %>
  <br />
  <%= link_to "Show", artist_path(artist) %> |
  <%= link_to "Edit", edit_artist_path(artist) %> |
  <%= link_to "Delete", artist_path(artist), method: :delete %>
<% end %>
<br />
<hr />

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render "form", artist: @artist %>

<%= link_to "Back", artists_path %>

app/views/artists/show.html.erb
<h1>Artist Info</h1>
<h2><%= @artist.artist %></h2>
<h3><%= @artist.genre %></h3>
<h4><%= link_to "See Artist's Songs", artist_songs_path(@artist) %></h4>
<br />
<hr />
<%= link_to "Back to Artists List", artists_path %> |
<%= link_to 'Delete Artist', @artist, method: :delete %>

app/views/boards/_form.html.erb
<h4><%= @board.id ? 'Edit Billboard' : 'Create Billboard' %></h4>
<hr />
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Billboard</h1>

<%= render "form", board: @board %>

<%= link_to "Show", board_path(@board) %> |
<%= link_to "Back", boards_path %>

app/views/boards/index.html.erb
<h1>All Billboards</h1>
<%= link_to 'Create Billboard', new_board_path %>
<hr />
<% @boards.each do |board|%>
  <h4><%= board.name %></h4>
  <%= link_to "#{board.name}'s Songs", board_path(board) %> |
  <%= link_to "Edit Board", edit_board_path(board) %> |
  <%= link_to "Delete Board", board_path(board), method: :delete %>
<% end %>
<hr />

app/views/boards/new.html.erb
<h2>New Billboard</h2>

<%= render "form", board: @board %>

<%= link_to "Back", boards_path %>

app/views/boards/show.html.erb
<h1><%= @board.name %></h1>
<h4><%= @board.description %></h4>
<h5>Board id: <%= @board.id %></h5>
<% @board_songs.each do |song|%>
 <%= song.song %>
<%end%>

<hr />
<%= link_to "Back to Billboards", boards_path %> |
<%= link_to 'Delete BillBoard', @board, method: :delete %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Artists', artists_path %> |
<%= link_to 'Billboard', boards_path %>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="ui container"> 
    <%= render 'layouts/navbar' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<h3><%= @song.id ? 'Edit Song' : 'Create Song' %></h3>
<hr />
<%= form_with(model: [@artist, @song], local: true, class: "ui form") do |f| %>
  <%= f.label :song %>
  <%= f.text_field :song, required: true %>
  <br />
  <%= f.label :board_id %>
  <%= f.text_field :board_id %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/songs/edit.html.erb
<%= render "form", artist: @artist, song: @song %>

<%= link_to "Back", artist_songs_path(@artist) %>

app/views/songs/index.html.erb
<h1><%= @artist.artist %></h1>
<%= link_to 'Add Song', new_artist_song_path(@artist) %>
<ul>
  <% @songs.each do |song| %>
    <li><%= link_to song.song, [@artist, song] %></li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render "form", artist: @artist, song: @song %>

<%= link_to "Back", artist_songs_path(@artist) %>

app/views/songs/show.html.erb
<h1><%= @artist.artist %></h1>
<h3>Song Name: <%= @song.song %></h3>
<h3>Song Rank: <%= @song.song_rank %></h3>
<hr />
<br />
<%= link_to 'Edit Song', edit_artist_song_path([@artist, @song]) %> |
<%= link_to 'Delete Song', [@artist, @song], method: :delete %> |
<%= link_to 'Back To Songs', artist_songs_path(@artist) %> |